# Generated by Django 5.0.4 on 2024-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videomodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
