# Generated by Django 5.0.4 on 2024-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_commet_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
